---
title: "Week 6 Example Analysis"
author: "Alijah"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r packages}

library(partykit)
library(ggplot2)

```




```{r load}

#Set seed to make results reproducible 
set.seed(20230802)

#Load the data
data<-read.csv("Week 6/Week 6 Example Data.csv")

#Set the categorical variables as factors 
data$PIN<-as.factor(data$PIN)
data$shareAmount<-as.factor(data$shareAmount)
data$shareType<-as.factor(data$shareType)
data$dollChoice<-as.factor(data$dollChoice)

```


## Decision Tree 
Predict participant doll choice from age and experimental conditions using a decision tree
```{r dectree}

#Fit the decision tree
tree<-ctree(dollChoice~age+shareAmount+shareType, data=data)

#Plot the decision tree 
plot(tree)
```


## Cluster Analysis
Assessing whether childeren cluster according to food prefs
```{r cluster}

#Plotting
pickyPlot<-ggplot(data=data, 
                  aes(x=pickyVeg,
                      y=pickyFruit))+
  labs(x="Pickiness about veggies",
       y="Pickiness about fruits")+
  theme_gray(base_size = 20)+
  geom_jitter()

#fit the cluster analysis
kFit<-kmeans(data[,3:4],centers=3)

#Extract means of clusters
kCenters<-kFit$centers

#Assign cluster to our data 

data$cluster<-as.factor(kFit$cluster)

#PLot Data 

pickyPlot<-pickyPlot+
  aes(color=data$cluster)+
  labs(color="k-Means Cluster")


```

